version: '3.3'
volumes:
  craftcms-data: null
  mariadb-data: null
  redis-data: null
  craftcms-logs: null
services:
  web:
    # image: 'tonyclemmey/craftcms-docker:craft2'
    build: .
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'craftcms-logs:/var/log'
      - 'craftcms-data:/var/www/web/uploads'
    links:
      - mariadb
      - redis
    environment:
      LANG: C.UTF-8
      REDIS_HOST: redis
      REDIS_PORT_6379_TCP: 'tcp://redis:6379'
      DB_HOST: mariadb
      DB_NAME: craft
      DB_PORT: 3306
      DB_USER: craft
      DB_PASS: secret
  mariadb:
    image: 'mariadb:10.4.12'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: craft
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: craft
    volumes:
      - 'mariadb-data:/var/lib/mysql/data'
  redis:
    image: 'redis:5.0.8-alpine'
    volumes:
      - 'redis-data:/data'
